In [1]:
import pandas as pd
import numpy as np

In [3]:
shootings_2023 = pd.read_csv("gunviolencearchive_2023.csv") # unfortunately the operations column
# ended up as NaN for all - in the web archive "Operations" has links to incident details (drive-by, etc) 
# as well as the ages of the people involved, weapon type, where it took place (bar/club, etc)
shootings_2023.head()

,Incident ID,Incident Date,State,City Or County,Address,Victims Killed,Victims Injured,Suspects Killed,Suspects Injured,Suspects Arrested,Operations
0,2792171,"December 31, 2023",Ohio,Cincinnati,7800 block of Dawn Rd,1,0,0,0,1,NaN
1,2792333,"December 31, 2023",New Hampshire,Manchester,274 Amherst St,1,0,0,0,1,NaN
2,2790984,"December 31, 2023",Tennessee,Memphis,3302 block of River Valley Ln,1,0,0,0,0,NaN
3,2793054,"December 31, 2023",Indiana,Fredericksburg,6000 block of W Mt Carmel Rd,1,0,0,0,0,NaN
4,2790802,"December 31, 2023",New Mexico,Albuquerque,6600 block of Moore Dr SW,1,0,0,0,1,NaN

In [7]:
shootings_2023[shootings_2023["Victims Killed"] + shootings_2023["Victims Injured"] > 4]
# gun violence archive defines a mass shooting as any where victims killed/injured exceeds 4 and takes
# place in one location

,Incident ID,Incident Date,State,City Or County,Address,Victims Killed,Victims Injured,Suspects Killed,Suspects Injured,Suspects Arrested,Operations
8,2790854,"December 31, 2023",California,Hawthorne,14125 Crenshaw Blvd,1,5,0,0,0,NaN
75,2790633,"December 30, 2023",Texas,Beaumont,6500 block of Bigner Rd,1,4,0,0,0,NaN
337,2786002,"December 24, 2023",Florida,Orlando (Lockhart),2800 block of Sudman Way,2,3,0,0,0,NaN
384,2786038,"December 24, 2023",Texas,Houston,5828 Martin Luther King Blvd,1,4,0,0,0,NaN
387,2787693,"December 24, 2023",Texas,Houston,8627 Glenvista St,1,4,0,0,1,NaN
442,2786253,"December 23, 2023",Texas,Fort Worth,9325 Cynthia Ct,1,4,0,0,0,NaN
443,2785646,"December 23, 2023",Maryland,Gwynn Oak (Woodlawn),1808 Woodlawn Dr,1,4,0,0,0,NaN
743,2779489,"December 15, 2023",Tennessee,Memphis,3941 Riverdale Rd,2,3,0,0,1,NaN
747,2779676,"December 15, 2023",California,Los Angeles,238 E El Segundo Blvd,1,4,0,0,0,NaN
1130,2771255,"December 5, 2023",Texas,Austin,7104 Berkman Dr,6,3,0,0,1,NaN
1185,2770296,"December 4, 2023",South Carolina,Lugoff,I-20,1,4,0,0,0,NaN
1194,2769819,"December 3, 2023",Texas,Dallas,9700 block of Royce Dr,4,1,1,0,0,NaN
1350,2768663,"December 1, 2023",Nevada,Las Vegas,E Charleston Blvd and N Honolulu St,2,3,0,0,2,NaN
1791,2761566,"November 21, 2023",Pennsylvania,Philadelphia,3200 block of Fairhill St,2,5,0,0,0,NaN
1895,2758871,"November 18, 2023",Tennessee,Memphis,3636 Field Lark Dr,4,1,1,0,0,NaN