In [8]:
import pandas as pd
import numpy as np

In [9]:
gva_shootings_2023 = pd.read_csv("gunviolencearchive_2023.csv") # unfortunately the operations column
# ended up as NaN for all - in the web archive "Operations" has links to incident details (drive-by, etc) 
# as well as the ages of the people involved, weapon type, where it took place (bar/club, etc)
gva_shootings_2023.head()

,Incident ID,Incident Date,State,City Or County,Address,Victims Killed,Victims Injured,Suspects Killed,Suspects Injured,Suspects Arrested,Operations
0,2792171,"December 31, 2023",Ohio,Cincinnati,7800 block of Dawn Rd,1,0,0,0,1,NaN
1,2792333,"December 31, 2023",New Hampshire,Manchester,274 Amherst St,1,0,0,0,1,NaN
2,2790984,"December 31, 2023",Tennessee,Memphis,3302 block of River Valley Ln,1,0,0,0,0,NaN
3,2793054,"December 31, 2023",Indiana,Fredericksburg,6000 block of W Mt Carmel Rd,1,0,0,0,0,NaN
4,2790802,"December 31, 2023",New Mexico,Albuquerque,6600 block of Moore Dr SW,1,0,0,0,1,NaN

In [11]:
gva_shootings_2023[gva_shootings_2023["Victims Killed"] + gva_shootings_2023["Victims Injured"] > 4].head()
# gun violence archive defines a mass shooting as any where victims killed/injured exceeds 4 and takes
# place in one location

,Incident ID,Incident Date,State,City Or County,Address,Victims Killed,Victims Injured,Suspects Killed,Suspects Injured,Suspects Arrested,Operations
8,2790854,"December 31, 2023",California,Hawthorne,14125 Crenshaw Blvd,1,5,0,0,0,NaN
75,2790633,"December 30, 2023",Texas,Beaumont,6500 block of Bigner Rd,1,4,0,0,0,NaN
337,2786002,"December 24, 2023",Florida,Orlando (Lockhart),2800 block of Sudman Way,2,3,0,0,0,NaN
384,2786038,"December 24, 2023",Texas,Houston,5828 Martin Luther King Blvd,1,4,0,0,0,NaN
387,2787693,"December 24, 2023",Texas,Houston,8627 Glenvista St,1,4,0,0,1,NaN

In [13]:
mj_shootings = pd.read_csv("Mother Jones - Mass Shootings Database, 1982 - 2024 - Sheet1.csv")
mj_shootings.head()

,case,location,date,summary,fatalities,injured,total_victims,location.1,age_of_shooter,prior_signs_mental_health_issues,...,weapon_details,race,gender,sources,mental_health_sources,sources_additional_age,latitude,longitude,type,year
0,Apalachee High School shooting,"Winder, Georgia",9/4/24,"Colt Gray, 14, was apprehended by responding p...",4,9,13,School,14,yes,...,AR-15,White,M,https://www.nbcnews.com/news/us-news/suspect-c...,https://www.washingtonpost.com/nation/2024/09/...,-,-,-,mass,2024
1,Arkansas grocery store shooting,"Fordyce, Arkansas",6/21/24,"Travis Posey, 44, opened fire in the parking l...",4,10,14,workplace,44,-,...,12-gauge shotgun,White,M,https://apnews.com/article/shooting-fordyce-ma...,-,-,-,-,mass,2024
2,UNLV shooting,"Las Vegas, Nevada",12/6/23,"Anthony Polito, 67, a former university profes...",3,1,4,School,67,-,...,-,White,M,https://www.nbcnews.com/news/us-news/anthony-p...,-,-,-,-,mass,2023
3,Maine bowling alley and bar shootings,"Lewiston, Maine",10/25/23,"Robert Card, 40, an Army reservist and firearm...",18,13,31,Other,40,yes,...,AR-15-style rifle (Rugar SFAR),White,M,https://www.washingtonpost.com/nation/2023/10/...,https://www.nytimes.com/article/lewiston-maine...,-,-,-,Spree,2023
4,Jacksonville Dollar General store shooting,"Jacksonville, Florida",8/26/23,"Ryan Palmeter, 21, outfitted in body armor, fa...",3,0,3,workplace,21,yes,...,AR-15-style rifle; Glock pistol,White,M,https://www.washingtonpost.com/nation/2023/08/...,https://www.nbcnews.com/news/us-news/live-blog...,-,-,-,mass,2023

In [15]:
mj_shootings.iloc[0]

case                                                   Apalachee High School shooting
location                                                              Winder, Georgia
date                                                                           9/4/24
summary                             Colt Gray, 14, was apprehended by responding p...
fatalities                                                                          4
injured                                                                             9
total_victims                                                                      13
location.1                                                                     School
age_of_shooter                                                                     14
prior_signs_mental_health_issues                                                  yes
mental_health_details                                                               -
weapons_obtained_legally                                                            -
where_obtained                                                                      -
weapon_type                                                       semiautomatic rifle
weapon_details                                                                  AR-15
race                                                                            White
gender                                                                              M
sources                             https://www.nbcnews.com/news/us-news/suspect-c...
mental_health_sources               https://www.washingtonpost.com/nation/2024/09/...
sources_additional_age                                                              -
latitude                                                                            -
longitude                                                                           -
type                                                                             mass
year                                                                             2024
Name: 0, dtype: object